#!/bin/sh

if [ -d '/etc/skel/Pictures/Sample Pictures' ]; then
	rm -rf '/etc/skel/Pictures/Sample Pictures'
fi
ln -s '/usr/share/feren-os/Sample Pictures' '/etc/skel/Pictures/Sample Pictures'
#for file in /home/*; do
#done
glib-compile-schemas /usr/share/glib-2.0/schemas
rm -f /usr/share/feren-os/1804tweaks/feren-settings-changed /usr/share/feren-os/1804tweaks/feren-settings-changed-2018 /usr/share/feren-os/1804tweaks/feren-settings-changed-2k18
